from django.urls import path
from . import views

urlpatterns = [
        path('home/',views.Hompage),
        path('merchant_login/',views.merchant_login),
        path('merchant_register/',views.merchant_register),
        path('merchant_home/',views.merchant_home),
        path('merchant_saved_coupons/',views.merchant_saved_coupons),
        path('merchant_business/',views.merchant_business),
        path('merchantprofile/',views.merchantprofile),
        path('merchant_logout/',views.merchant_logout),
        path('logouthome/',views.logouthome),
        path('user_logout/',views.user_logout),
        path('viewdeals/',views.viewdeals), 
        path('viewcoupons/',views.viewcoupons),
        path('fseparate/',views.foodseparate),
        path('fall/',views.foodall),
        path('clothingseparate/',views.clothingseparate),
        path('clothingall/',views.clothingall),
        path('saloonseparate/',views.saloonseparate),
        path('saloonall/',views.saloonall),
        path('groceriesall/',views.groceriesall),
        path('teseparate/',views.teseparate),
        path('teall/',views.teall),
        path('jseparate/',views.jseparate),
        path('jall/',views.jall),
        path('meseparate/',views.meseparate),
        path('meall/',views.meall),
        path('hkseparate/',views.hkseparate),
        path('hkall/',views.hkall),
        path('store/',views.stores),
        path('search/',views.searchall),
        path('allstore/',views.allstore),
        path('separatestore/',views.separatestore),
        path('displaystores/',views.displaystores),
        path('about/',views.about),
        path('emailverify/', views.EmailVerify),
        path('forgotpassword/',views.ForgotPassword),
        path('expiryemailhash/',views.CreateExpiryEmailHash),
        path('email/verify/',views.VerifyEmailHash),
        path('contact/', views.contact)
]